Feature: This fixes all bugs

    Scenario:
        [Solved]            Given that after increasing size to the sizes it fails to be trully responsive it should readapt the layout to the fill window size.
        [Solved]            Given that currently only settings allow to add cities the definitive expected solution is to have both from time visualizer and settings window the ability to add cities to the list of clocks
        [Solved]            Given that the current clocks of time visualizer show single clock when multiple windows are selected this bug should show for instance 12:00 - 1:30 pm when spanned window is selected. This is for time visualizer. Use @images/wtb4.png as reference
        [Solved]            Given that the search textbox should support acronyms and cities names please add a better implementation that actually works given that currently the search location/timezone search is not working as shown in the @images/wtb3.png picture.
                            In order to fix search box to have support of all cities and acronyms of cities I'm looking for something like UN/LOCODE like having ,US,BOG,Bogota,Bogota, but in this database of locations/timezones it doesn't have the timezone as UTC+5 so do you know if its possible to have a better more complete one for something ?
                            Use the generated citiesdb from @WorldClock/citiesdb/data
        [Solved]            Given that some text colors have good contrast for dark themes when changing to light themes color is not readable, both text with and without glow, sometimes glow is making it harder to read. Yellow is not visible in any light mode. Please change this given that yellow text need more contrast or glow or something to be fully fixed.
        [Solved]            Given that currently is not fully functional the search textbox of time visualizer please fix it fully adapt the time converter and the settings window to have the same searchbox making both approaches work as expected.
        [Solved]            Given that currently we called the timeline "Time Translator", lets change that term in all code and al references also in feature files for "Time Visualizer"
        [Solved]            Make the default status of Time Visualizer as unfolded as default behaviour
        [Solved]            Given that Keyboard nav is still buggy in time visualizer, enter and arrows are not showing the selection change nor adding the clock correspondingly, remmber arrows should change the focused item and enter should add the clock
        [Solved]            Given that the expected set value for transparency please set to be 50% not 10% right after opening the settings window. Instead of using black as font color in light mode make all clocks in all cards even inside time visualizer have same hue but bit more darker in all light themes buyt remmember to keep somehow the style and color set in darkmodes but with the shade (more dark in value but keeping hue and saturation) for light themes
        [Solved]            Given that Time Visualizer should not be limited vertically it should show all clocks apropiatetly and fully in the right 
        [Solved]            Given that currently the UTC card in the time visualizer is duplicated please keep only the light blue one. 
        [Solved]            Given that Currently the listbox is not working the keyboard nav arrows but enter is working, items should change focus and show selected item before clicking enter as hover does
        [Solved]            Given that currently is not possible to set the home location please add a feature with proper icons to set the home location and show the time difference in ours for each card in all cards.
        [Solved]            Given that Currently from 8 cards that should be dispayed both in the generl and in the time visualizer, it can only be seen 4 cards in the time visualizer, not sure if theres a limit to display things vertically (which should be removed) or a limit on cards (which should also be removed)
        [Solved]            Given that currently the space of the general cards in Clocks section is narrow, when collapsed the time visualizer most of the window is showing only the background, please fix this by making the visualization more dynamic, create a simple animation when time visualizer is collapsed, make the common clocks increase the layout size of clocks, even making clocks be wider and position in the middle of the window, and revert to default sizes when uncollapsed 
        [Solved]            Given the feature of animation of clocks, right after clicking that collapsable of time visualizer, the button to uncollapse again is lost, addinitionally when finishing the animation rearrange cards in a grid view, with a smooth final additional animation, this final animation should be similar as an after effects of sorting animation witho , but remmeber to always show the button to uncollapse time visualizer in this focus mode
        [Solved]            Given that light themes have a colorset completely different, change text colors for all cards all clocks preserving same hue but having the apropiate value and keeping a similar saturation for both text color and also filled boxes for timeline
        [Solved]            Given that currently size of window doesn't resize elements to fit the window, and there's vertical scroll for the main window, please instead of having verticall scrollable please adjust the size of the elements to always fit the window size preserving visibility of all texts and  
        [Solved]            Given that the height of the rows in the time visualizer are to tall we need to remove. Rows should have only two horizontal lines of text, no more, as shown in @file:wtb.png, replicate the in the first column City name, city country, in the second column time span, date span, and in the third column the dates with a similar view of dates and times am and pm so that its possible to have as good as @file:wtb3.png  indicating date change in second column, indicating week day in the third column and having a better two horizontal line time calendar for each row. 
                            As in WTB the timeline should have for each cell the corresponding time and if its am or pm 
        [Solved]            Given that clocks left section should be scaled smaller in such a way that combining all heights, the cumulative effective height is exactly the same as timeline, make them fit to have exactly this behaviour, even after adding new clocks both elements (clock section and time visualizer section) should fit in the exact same height.
                            Remmember that nevertheless this should preserve congruency with heights, when there are many clocks (9 or more) text starts to be displayed squized without properly resizing the effective window height, available height should be set increased so that this doesn't happends
        [Solved]            The first row of timeline cells should coincide with the home location visualization of hours.
        [Solved]            Clocks by city should appear only once, if same location was already present don't do anything, nor popup nor adding any new city
        [Solved]            Instead of -1d it should have the reference from home location and detect wether any location has visibility of next day in the same timeline, if so with a highlighted type of color more visible it should appear +1d on corresponding clocks instead of -1d in other days.
        [Solved]            As shown in @file:wtbmca.png when there is change of date in the timeline, instead of 12 am it should show the weekday on he top of the merged cell pair and instead of 12am change to Month and date, so it would be May 1 instead of 12 am, use short version of month